baseURL: https://marc-k-etherington.github.io/
languageCode: en-us
defaultContentLanguage: en
title: Etherington Research Group
theme: papercss-hugo-theme
enableRobotsTXT: true

privacy:
  disqus:
    disable: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

# To disable, set to an extremely large value, such as 999999
pagination.pagerSize: 999999

params:
  homeMetaContent: A Hugo theme made with PaperCSS, the less formal CSS framework.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2 January 2006
  ShowDatesOnPosts: true
  navTitleLink: /


menu:
  nav:
    - name: News
      url: /
      weight: 1
    - name: Marc Etherington
      url: /marc-etherington
      weight: 2
    - name: Group
      url: /group
      weight: 3
    - name: Research
      url: /research
      weight: 4
    - name: Teaching
      url: /teaching
      weight: 5
    - name: Publications
      url: /publications
      weight: 6
    - name: Seminars
      url: /seminars
      weight: 7
  

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
