baseURL = 'https://marc-k-etherington.github.io/'
languageCode = 'en-us'
title = 'The Etherington Group'
theme = 'papercss-hugo-theme'


menu =
  nav =
    - name: Research
      url: /research
      weight = 1
    - name = Tags
      url = /tags/
      weight = 2
    - name = About
      url = /about/
      weight = 3
    
